name = "keita-license-api"
main = "worker.js"
compatibility_date = "2026-09-13"

[vars]
ALLOWED_ORIGINS = "https://keitaphotocamerakathu-sudo.github.io"

[[d1_databases]]
binding = "DB"
database_name = "keita-license"
database_id = "a7bb4421-0d73-475c-b657-42e10b3d0665"
